const fs = require('fs')
let c = fs.readFileSync('src/components/layout/Layout.jsx', 'utf8')
c = c.replace(/color: active \? '#fff' : 'rgba\(255,255,255,0\.7\)'/g, "color: '#fff'")
fs.writeFileSync('src/components/layout/Layout.jsx', c)
console.log('Done!')